# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GitHub_Home_Tasks\TRPO_Desktop\app\Frontend\windown2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1254, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_Central = QtWidgets.QFrame(self.centralwidget)
        self.frame_Central.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Central.setObjectName("frame_Central")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Central)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_ColumnLeft = QtWidgets.QFrame(self.frame_Central)
        self.frame_ColumnLeft.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame_ColumnLeft.setStyleSheet("")
        self.frame_ColumnLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ColumnLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ColumnLeft.setObjectName("frame_ColumnLeft")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_ColumnLeft)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_ColumnLeft)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_6.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_ColumnLeft)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.frame_7)
        self.frame.setMinimumSize(QtCore.QSize(0, 2))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: #e9e9ee;\n"
"    border:0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6.addWidget(self.frame)
        self.gridLayout_6.addWidget(self.frame_7, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_ColumnLeft)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_Central)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.page0)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_Title = QtWidgets.QLabel(self.frame_2)
        self.label_Title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_Title.setStyleSheet("QLabel{\n"
"\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout_9.addWidget(self.label_Title)
        self.label_SubTitle = QtWidgets.QLabel(self.frame_2)
        self.label_SubTitle.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_SubTitle.setStyleSheet("QLabel{\n"
"\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitle.setObjectName("label_SubTitle")
        self.verticalLayout_9.addWidget(self.label_SubTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout = QtWidgets.QGridLayout(self.page1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_Alfandega = QtWidgets.QFrame(self.page1)
        self.frame_Alfandega.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega.setObjectName("frame_Alfandega")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_Alfandega)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_24 = QtWidgets.QFrame(self.frame_Alfandega)
        self.frame_24.setStyleSheet("QFrame{ border:0px }")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_19 = QtWidgets.QFrame(self.frame_24)
        self.frame_19.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_19.setStyleSheet("QFrame{ border:0px }")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_TitleAlfandega = QtWidgets.QLabel(self.frame_19)
        self.label_TitleAlfandega.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_TitleAlfandega.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_TitleAlfandega.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TitleAlfandega.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega.setObjectName("label_TitleAlfandega")
        self.verticalLayout_11.addWidget(self.label_TitleAlfandega)
        self.horizontalLayout_11.addWidget(self.frame_19)
        self.verticalLayout_14.addWidget(self.frame_24)
        self.frame_23 = QtWidgets.QFrame(self.frame_Alfandega)
        self.frame_23.setStyleSheet("QFrame{ border:0px }")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.textEdit = QtWidgets.QTextEdit(self.frame_23)
        self.textEdit.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_15.addWidget(self.textEdit)
        self.verticalLayout_14.addWidget(self.frame_23)
        self.gridLayout.addWidget(self.frame_Alfandega, 0, 0, 1, 1)
        self.frame_Alfandega_3 = QtWidgets.QFrame(self.page1)
        self.frame_Alfandega_3.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega_3.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega_3.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega_3.setObjectName("frame_Alfandega_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_Alfandega_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_3 = QtWidgets.QFrame(self.frame_Alfandega_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(20, 10, 251, 71))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_SubTitleAlfandega = QtWidgets.QLabel(self.frame_5)
        self.label_SubTitleAlfandega.setGeometry(QtCore.QRect(10, 20, 371, 18))
        self.label_SubTitleAlfandega.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega.setObjectName("label_SubTitleAlfandega")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(290, 10, 801, 71))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(10, 11, 771, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(20, 100, 341, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton_BtnAlfandega_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_BtnAlfandega_3.setGeometry(QtCore.QRect(50, 10, 234, 50))
        self.pushButton_BtnAlfandega_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_3.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_3.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/path395.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_BtnAlfandega_3.setIcon(icon)
        self.pushButton_BtnAlfandega_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_3.setObjectName("pushButton_BtnAlfandega_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(370, 100, 341, 80))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton_BtnAlfandega_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_BtnAlfandega_4.setGeometry(QtCore.QRect(60, 10, 234, 50))
        self.pushButton_BtnAlfandega_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_4.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_4.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_4.setIcon(icon)
        self.pushButton_BtnAlfandega_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_4.setObjectName("pushButton_BtnAlfandega_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setGeometry(QtCore.QRect(720, 100, 371, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.pushButton_BtnAlfandega_5 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_BtnAlfandega_5.setGeometry(QtCore.QRect(70, 10, 234, 50))
        self.pushButton_BtnAlfandega_5.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_5.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_5.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_5.setIcon(icon)
        self.pushButton_BtnAlfandega_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_5.setObjectName("pushButton_BtnAlfandega_5")
        self.verticalLayout_18.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame_Alfandega_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_Alfandega_6 = QtWidgets.QFrame(self.page2)
        self.frame_Alfandega_6.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega_6.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega_6.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega_6.setObjectName("frame_Alfandega_6")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_Alfandega_6)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_43 = QtWidgets.QFrame(self.frame_Alfandega_6)
        self.frame_43.setStyleSheet("QFrame{ border:0px }")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_43)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_44 = QtWidgets.QFrame(self.frame_43)
        self.frame_44.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_44.setStyleSheet("QFrame{ border:0px }")
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_TitleAlfandega_9 = QtWidgets.QLabel(self.frame_44)
        self.label_TitleAlfandega_9.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega_9.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega_9.setObjectName("label_TitleAlfandega_9")
        self.verticalLayout_36.addWidget(self.label_TitleAlfandega_9)
        self.label_SubTitleAlfandega_9 = QtWidgets.QLabel(self.frame_44)
        self.label_SubTitleAlfandega_9.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega_9.setObjectName("label_SubTitleAlfandega_9")
        self.verticalLayout_36.addWidget(self.label_SubTitleAlfandega_9)
        self.horizontalLayout_19.addWidget(self.frame_44)
        self.verticalLayout_35.addWidget(self.frame_43)
        self.frame_45 = QtWidgets.QFrame(self.frame_Alfandega_6)
        self.frame_45.setStyleSheet("QFrame{ border:0px }")
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.pushButton_BtnAlfandega_9 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_BtnAlfandega_9.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_9.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_9.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_9.setIcon(icon)
        self.pushButton_BtnAlfandega_9.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_9.setObjectName("pushButton_BtnAlfandega_9")
        self.verticalLayout_37.addWidget(self.pushButton_BtnAlfandega_9)
        self.verticalLayout_35.addWidget(self.frame_45)
        self.gridLayout_5.addWidget(self.frame_Alfandega_6, 0, 0, 1, 1)
        self.frame_Alfandega_4 = QtWidgets.QFrame(self.page2)
        self.frame_Alfandega_4.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega_4.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega_4.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega_4.setObjectName("frame_Alfandega_4")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_Alfandega_4)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_37 = QtWidgets.QFrame(self.frame_Alfandega_4)
        self.frame_37.setStyleSheet("QFrame{ border:0px }")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_38.setStyleSheet("QFrame{ border:0px }")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_TitleAlfandega_7 = QtWidgets.QLabel(self.frame_38)
        self.label_TitleAlfandega_7.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega_7.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega_7.setObjectName("label_TitleAlfandega_7")
        self.verticalLayout_30.addWidget(self.label_TitleAlfandega_7)
        self.label_SubTitleAlfandega_7 = QtWidgets.QLabel(self.frame_38)
        self.label_SubTitleAlfandega_7.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega_7.setObjectName("label_SubTitleAlfandega_7")
        self.verticalLayout_30.addWidget(self.label_SubTitleAlfandega_7)
        self.horizontalLayout_17.addWidget(self.frame_38)
        self.verticalLayout_29.addWidget(self.frame_37)
        self.frame_39 = QtWidgets.QFrame(self.frame_Alfandega_4)
        self.frame_39.setStyleSheet("QFrame{ border:0px }")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.pushButton_BtnAlfandega_7 = QtWidgets.QPushButton(self.frame_39)
        self.pushButton_BtnAlfandega_7.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_7.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_7.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_7.setIcon(icon)
        self.pushButton_BtnAlfandega_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_7.setObjectName("pushButton_BtnAlfandega_7")
        self.verticalLayout_31.addWidget(self.pushButton_BtnAlfandega_7)
        self.verticalLayout_29.addWidget(self.frame_39)
        self.gridLayout_5.addWidget(self.frame_Alfandega_4, 0, 1, 1, 1)
        self.frame_Alfandega_5 = QtWidgets.QFrame(self.page2)
        self.frame_Alfandega_5.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega_5.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega_5.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega_5.setObjectName("frame_Alfandega_5")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_Alfandega_5)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_40 = QtWidgets.QFrame(self.frame_Alfandega_5)
        self.frame_40.setStyleSheet("QFrame{ border:0px }")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_41.setStyleSheet("QFrame{ border:0px }")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_TitleAlfandega_8 = QtWidgets.QLabel(self.frame_41)
        self.label_TitleAlfandega_8.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega_8.setStyleSheet("QLabel{\n"
"text-align:centeral;\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:45px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega_8.setObjectName("label_TitleAlfandega_8")
        self.verticalLayout_33.addWidget(self.label_TitleAlfandega_8)
        self.label_SubTitleAlfandega_8 = QtWidgets.QLabel(self.frame_41)
        self.label_SubTitleAlfandega_8.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega_8.setObjectName("label_SubTitleAlfandega_8")
        self.verticalLayout_33.addWidget(self.label_SubTitleAlfandega_8)
        self.horizontalLayout_18.addWidget(self.frame_41)
        self.verticalLayout_32.addWidget(self.frame_40)
        self.frame_42 = QtWidgets.QFrame(self.frame_Alfandega_5)
        self.frame_42.setStyleSheet("QFrame{ border:0px }")
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.pushButton_BtnAlfandega_8 = QtWidgets.QPushButton(self.frame_42)
        self.pushButton_BtnAlfandega_8.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_8.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_8.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_8.setIcon(icon)
        self.pushButton_BtnAlfandega_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_8.setObjectName("pushButton_BtnAlfandega_8")
        self.verticalLayout_34.addWidget(self.pushButton_BtnAlfandega_8)
        self.verticalLayout_32.addWidget(self.frame_42)
        self.gridLayout_5.addWidget(self.frame_Alfandega_5, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_Alfandega_9 = QtWidgets.QFrame(self.page3)
        self.frame_Alfandega_9.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega_9.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega_9.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega_9.setObjectName("frame_Alfandega_9")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_Alfandega_9)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.frame_52 = QtWidgets.QFrame(self.frame_Alfandega_9)
        self.frame_52.setStyleSheet("QFrame{ border:0px }")
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_52)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_53 = QtWidgets.QFrame(self.frame_52)
        self.frame_53.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_53.setStyleSheet("QFrame{ border:0px }")
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.frame_53)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_TitleAlfandega_12 = QtWidgets.QLabel(self.frame_53)
        self.label_TitleAlfandega_12.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega_12.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega_12.setObjectName("label_TitleAlfandega_12")
        self.verticalLayout_45.addWidget(self.label_TitleAlfandega_12)
        self.label_SubTitleAlfandega_12 = QtWidgets.QLabel(self.frame_53)
        self.label_SubTitleAlfandega_12.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega_12.setObjectName("label_SubTitleAlfandega_12")
        self.verticalLayout_45.addWidget(self.label_SubTitleAlfandega_12)
        self.horizontalLayout_22.addWidget(self.frame_53)
        self.verticalLayout_44.addWidget(self.frame_52)
        self.frame_54 = QtWidgets.QFrame(self.frame_Alfandega_9)
        self.frame_54.setStyleSheet("QFrame{ border:0px }")
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.frame_54)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.pushButton_BtnAlfandega_12 = QtWidgets.QPushButton(self.frame_54)
        self.pushButton_BtnAlfandega_12.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_12.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_12.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_12.setIcon(icon)
        self.pushButton_BtnAlfandega_12.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_12.setObjectName("pushButton_BtnAlfandega_12")
        self.verticalLayout_46.addWidget(self.pushButton_BtnAlfandega_12)
        self.verticalLayout_44.addWidget(self.frame_54)
        self.gridLayout_4.addWidget(self.frame_Alfandega_9, 0, 0, 1, 1)
        self.frame_Alfandega_7 = QtWidgets.QFrame(self.page3)
        self.frame_Alfandega_7.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega_7.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega_7.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega_7.setObjectName("frame_Alfandega_7")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_Alfandega_7)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.frame_46 = QtWidgets.QFrame(self.frame_Alfandega_7)
        self.frame_46.setStyleSheet("QFrame{ border:0px }")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_46)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_47 = QtWidgets.QFrame(self.frame_46)
        self.frame_47.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_47.setStyleSheet("QFrame{ border:0px }")
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_47)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_TitleAlfandega_10 = QtWidgets.QLabel(self.frame_47)
        self.label_TitleAlfandega_10.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega_10.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega_10.setObjectName("label_TitleAlfandega_10")
        self.verticalLayout_39.addWidget(self.label_TitleAlfandega_10)
        self.label_SubTitleAlfandega_10 = QtWidgets.QLabel(self.frame_47)
        self.label_SubTitleAlfandega_10.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega_10.setObjectName("label_SubTitleAlfandega_10")
        self.verticalLayout_39.addWidget(self.label_SubTitleAlfandega_10)
        self.horizontalLayout_20.addWidget(self.frame_47)
        self.verticalLayout_38.addWidget(self.frame_46)
        self.frame_48 = QtWidgets.QFrame(self.frame_Alfandega_7)
        self.frame_48.setStyleSheet("QFrame{ border:0px }")
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_48)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.pushButton_BtnAlfandega_10 = QtWidgets.QPushButton(self.frame_48)
        self.pushButton_BtnAlfandega_10.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_10.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_10.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_10.setIcon(icon)
        self.pushButton_BtnAlfandega_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_10.setObjectName("pushButton_BtnAlfandega_10")
        self.verticalLayout_40.addWidget(self.pushButton_BtnAlfandega_10)
        self.verticalLayout_38.addWidget(self.frame_48)
        self.gridLayout_4.addWidget(self.frame_Alfandega_7, 0, 1, 1, 1)
        self.frame_Alfandega_8 = QtWidgets.QFrame(self.page3)
        self.frame_Alfandega_8.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega_8.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega_8.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega_8.setObjectName("frame_Alfandega_8")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_Alfandega_8)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.frame_49 = QtWidgets.QFrame(self.frame_Alfandega_8)
        self.frame_49.setStyleSheet("QFrame{ border:0px }")
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_49)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_50 = QtWidgets.QFrame(self.frame_49)
        self.frame_50.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_50.setStyleSheet("QFrame{ border:0px }")
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.frame_50)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_TitleAlfandega_11 = QtWidgets.QLabel(self.frame_50)
        self.label_TitleAlfandega_11.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega_11.setStyleSheet("QLabel{\n"
"text-align:centeral;\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:45px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega_11.setObjectName("label_TitleAlfandega_11")
        self.verticalLayout_42.addWidget(self.label_TitleAlfandega_11)
        self.label_SubTitleAlfandega_11 = QtWidgets.QLabel(self.frame_50)
        self.label_SubTitleAlfandega_11.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega_11.setObjectName("label_SubTitleAlfandega_11")
        self.verticalLayout_42.addWidget(self.label_SubTitleAlfandega_11)
        self.horizontalLayout_21.addWidget(self.frame_50)
        self.verticalLayout_41.addWidget(self.frame_49)
        self.frame_51 = QtWidgets.QFrame(self.frame_Alfandega_8)
        self.frame_51.setStyleSheet("QFrame{ border:0px }")
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.pushButton_BtnAlfandega_11 = QtWidgets.QPushButton(self.frame_51)
        self.pushButton_BtnAlfandega_11.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega_11.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega_11.setStyleSheet("QPushButton{\n"
"    text-align:centeral;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega_11.setIcon(icon)
        self.pushButton_BtnAlfandega_11.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega_11.setObjectName("pushButton_BtnAlfandega_11")
        self.verticalLayout_43.addWidget(self.pushButton_BtnAlfandega_11)
        self.verticalLayout_41.addWidget(self.frame_51)
        self.gridLayout_4.addWidget(self.frame_Alfandega_8, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.page3)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.gridLayout_3.addWidget(self.frame_Central, 0, 0, 1, 1)
        self.frame_ColumnCenter = QtWidgets.QFrame(self.centralwidget)
        self.frame_ColumnCenter.setGeometry(QtCore.QRect(18, 11, 24, 24))
        self.frame_ColumnCenter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ColumnCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ColumnCenter.setObjectName("frame_ColumnCenter")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_ColumnCenter)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Title.setText(_translate("MainWindow", "Привет"))
        self.label_SubTitle.setText(_translate("MainWindow", "Это приложение, которое парсит данные и формирует Exel таблицу с актуальными данными, так же заливает данные в облоко"))
        self.label_TitleAlfandega.setText(_translate("MainWindow", "Список данных в папке"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.label_SubTitleAlfandega.setText(_translate("MainWindow", "Введите номер документа"))
        self.pushButton_BtnAlfandega_3.setText(_translate("MainWindow", "Скачать"))
        self.pushButton_BtnAlfandega_4.setText(_translate("MainWindow", "Загрузить"))
        self.pushButton_BtnAlfandega_5.setText(_translate("MainWindow", "Выбрать другую папку"))
        self.label_TitleAlfandega_9.setText(_translate("MainWindow", "Обработать документ"))
        self.label_SubTitleAlfandega_9.setText(_translate("MainWindow", "Нажав на кнопку вы получите таблицу с обработанными данными"))
        self.pushButton_BtnAlfandega_9.setText(_translate("MainWindow", "Обработать "))
        self.label_TitleAlfandega_7.setText(_translate("MainWindow", "Создать документ"))
        self.label_SubTitleAlfandega_7.setText(_translate("MainWindow", "Нажав на кнопку вы получите документ в формате Exel"))
        self.pushButton_BtnAlfandega_7.setText(_translate("MainWindow", "Создать"))
        self.label_TitleAlfandega_8.setText(_translate("MainWindow", "Залить документ в облако"))
        self.label_SubTitleAlfandega_8.setText(_translate("MainWindow", "Нажав на кнопку вы зальете документ в облако"))
        self.pushButton_BtnAlfandega_8.setText(_translate("MainWindow", "Залить "))
        self.label_TitleAlfandega_12.setText(_translate("MainWindow", "Обработать документ"))
        self.label_SubTitleAlfandega_12.setText(_translate("MainWindow", "Нажав на кнопку вы получите таблицу с обработанными данными"))
        self.pushButton_BtnAlfandega_12.setText(_translate("MainWindow", "Обработать "))
        self.label_TitleAlfandega_10.setText(_translate("MainWindow", "Создать документ"))
        self.label_SubTitleAlfandega_10.setText(_translate("MainWindow", "Нажав на кнопку вы получите документ в формате Exel"))
        self.pushButton_BtnAlfandega_10.setText(_translate("MainWindow", "Создать"))
        self.label_TitleAlfandega_11.setText(_translate("MainWindow", "Залить документ в облако"))
        self.label_SubTitleAlfandega_11.setText(_translate("MainWindow", "Нажав на кнопку вы зальете документ в облако"))
        self.pushButton_BtnAlfandega_11.setText(_translate("MainWindow", "Залить "))
